# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GY/Works/ZYNQ/SummerSchool2022/pynq_cordic/project/cordic_vivado_prj/cordic_vivado_prj.srcs/sources_1/bd/design_1/ip/design_1_cordiccart2pol_0_0/design_1_cordiccart2pol_0_0.xci
# IP: The module: 'design_1_cordiccart2pol_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GY/Works/ZYNQ/SummerSchool2022/pynq_cordic/project/cordic_vivado_prj/cordic_vivado_prj.gen/sources_1/bd/design_1/ip/design_1_cordiccart2pol_0_0/constraints/cordiccart2pol_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cordiccart2pol_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/GY/Works/ZYNQ/SummerSchool2022/pynq_cordic/project/cordic_vivado_prj/cordic_vivado_prj.srcs/sources_1/bd/design_1/ip/design_1_cordiccart2pol_0_0/design_1_cordiccart2pol_0_0.xci
# IP: The module: 'design_1_cordiccart2pol_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GY/Works/ZYNQ/SummerSchool2022/pynq_cordic/project/cordic_vivado_prj/cordic_vivado_prj.gen/sources_1/bd/design_1/ip/design_1_cordiccart2pol_0_0/constraints/cordiccart2pol_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cordiccart2pol_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
